global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'fluxcache'
    static_configs:
      - targets: ['node1:8081', 'node2:8082', 'node3:8083']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics 