name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o fluxcache-linux-amd64 ./cmd/cache-node
        GOOS=darwin GOARCH=amd64 go build -o fluxcache-darwin-amd64 ./cmd/cache-node
        GOOS=windows GOARCH=amd64 go build -o fluxcache-windows-amd64.exe ./cmd/cache-node

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fluxcache-linux-amd64
          fluxcache-darwin-amd64
          fluxcache-windows-amd64.exe
        body: |
          ## FluxCache v${{ github.ref_name }}
          
          ### Features
          - Distributed in-memory cache with consistent hashing
          - 2x data replication and automatic failover
          - Node health monitoring and heartbeat detection
          - Conflict resolution for concurrent updates
          - REST API support
          - Docker containerization ready
          
          ### Performance
          - ~1,373 requests/sec
          - 6.6ms average latency
          - Competitive with etcd and Consul
          
          ### Installation
          Download the appropriate binary for your platform and run:
          ```bash
          ./fluxcache-linux-amd64
          ```
          
          ### Docker
          ```bash
          docker-compose -f Docker/docker-compose.yml up
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 